# Generated by Django 3.2.8 on 2021-10-13 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_teachers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teachers',
            new_name='Teacher',
        ),
    ]
