# Generated by Django 3.2.8 on 2021-10-20 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_application'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Application',
        ),
    ]
