# Generated by Django 3.2.8 on 2021-10-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='client_last_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Фамилия'),
        ),
    ]
